# Generated by Django 3.2.7 on 2021-10-06 11:30
'''
    This file was created using this command: //in the same level of the manage.py
    python manage.py makemigrations --empty --name students djangoreact_app
'''
#___________________________________________________________________________________
from django.db import migrations

#this is only to create data so that the data base isn't empty when we run the the API
def create_data(apps, schema_editor):
    Student = apps.get_model('djangoreact_app', 'Student')
    Student(name="Rahaf MH", email="email@email.com", document="1130272", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('djangoreact_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
